### ISSUE TITLE
Storybookのチュートリアルをやってみる

### ISSUE THREAD

**Issue by akm** [akm/typescript_sandbox#18]
https://github.com/akm/typescript_sandbox/issues/14#issuecomment-640011650 から派生したIssue。

https://www.learnstorybook.com/
Storybookは[以下のライブラリ/フレームワークに対応している](https://storybook.js.org/) ので、Reactだけやる

- React
- React Native
- Vue
- Angular
- Ember
- HTML
- Svelte
- Mithril
- Riot

**Comment by akm** [comment]
## Build a simple component

https://www.learnstorybook.com/intro-to-storybook/react/en/simple-component/

- CDD Component Driven Development
  https://blog.hichroma.com/component-driven-development-ce1109d56c8e
- Visual Test Driven Development
  https://blog.hichroma.com/visual-test-driven-development-aec1c98bed87

**Comment by akm** [comment]
## Assemble a composite component
https://www.learnstorybook.com/intro-to-storybook/react/en/composite-component/

TaskLIstの実装を変更したときにstorybookのsnapshotテストが失敗したのはなるほどと思った。
でも意図的に全部( `a` ) を選択しなきゃならなかったんだけど、勝手にテストを実行してくれるといいなー（`yarn test` 起動しっぱなしならいいのかな？ )

**Comment by akm** [comment]
## Wire in data
https://www.learnstorybook.com/intro-to-storybook/react/en/data/

Presentational and Container Components
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0

### redux以外の状態管理のライブラリ
- [Apollo](https://www.apollographql.com/client/)
    Apollo Client is the ultra-flexible, community-driven GraphQL client for React, JavaScript, and native platforms.
- [MobX](https://mobx.js.org/README.html)
    https://mobx.js.org/README.html

### reduxと一緒に使う場合

connectしたコンポーネントをstorybookで表示しようとすると以下のようにエラーになる。

<img width="1699" alt="スクリーンショット 2020-06-07 11 15 00 午前" src="https://user-images.githubusercontent.com/18912/83958741-514e0700-a8b0-11ea-88a2-d09075f7a49f.png">

```
Could not find "store" in the context of "Connect(PureTaskList)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(PureTaskList) in connect options.
Error: Could not find "store" in the context of "Connect(PureTaskList)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(PureTaskList) in connect options.
    at ConnectFunction (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:61588:15)
    at renderWithHooks (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:50759:18)
    at updateFunctionComponent (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:52990:20)
    at updateSimpleMemoComponent (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:52928:10)
    at updateMemoComponent (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:52817:14)
    at beginWork (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:54638:16)
    at HTMLUnknownElement.callCallback (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:36144:14)
    at Object.invokeGuardedCallbackDev (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:36193:16)
    at invokeGuardedCallback (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:36248:31)
    at beginWork$1 (http://localhost:9009/vendors~main.4ae235021f2ea83f32e9.bundle.js:59159:7)
```

なので、TaskList.stories.js では connectした `TaskList` ではなく、connectしていないPresentation Componentである `PureTaskList` を参照する

**Comment by akm** [comment]
## Test UI components

https://www.learnstorybook.com/intro-to-storybook/react/en/test/

chromatic
https://www.chromatic.com/

レビューの機能がついてて便利そう。

**Comment by akm** [comment]
## Addons

https://www.learnstorybook.com/intro-to-storybook/react/en/using-addons/

- [Knob](https://github.com/storybookjs/storybook/tree/master/addons/knobs)
  Storybook Addon Knobs allow you to edit props dynamically using the Storybook UI. You can also use Knobs as a dynamic variable inside stories in Storybook.

**Comment by akm** [comment]
## Creating addons

https://www.learnstorybook.com/intro-to-storybook/react/en/creating-addons/

チュートリアルでaddon作れるのか。

・・・どうにもうまく動かない。
https://github.com/chromaui/learnstorybook-code のmasterで `yarn storybook` しても以下のエラーでサーバが起動せず、ブラウザからアクセスできない

<details>
<summary> yarn storybook の出力</summary>

```
$ yarn storybook
yarn run v1.19.2
$ start-storybook -p 9009 -s public
info @storybook/react v5.3.18
info 
info => Loading static files from: /Users/takeshi/workspace/learnstorybook-code/public .
info => Loading presets
info => Loading presets
info => Loading config/preview file in "./.storybook".
info => Adding stories defined in ".storybook/main.js".
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack setup.
webpack built 92925a1b04b3b982ca9f in 11789ms
✖ ｢wdm｣: Hash: 92925a1b04b3b982ca9f
Version: webpack 4.43.0
Time: 11789ms
Built at: 2020-06-07 20:12:33
                                          Asset       Size        Chunks                                Chunk Names
                            asset-manifest.json  640 bytes                [emitted]                     
                                    iframe.html   2.87 KiB                [emitted]                     
            main.92925a1b04b3b982ca9f.bundle.js   60.5 KiB          main  [emitted] [immutable]         main
        main.92925a1b04b3b982ca9f.bundle.js.map     36 KiB          main  [emitted] [dev]               main
    runtime~main.92925a1b04b3b982ca9f.bundle.js   33.5 KiB  runtime~main  [emitted] [immutable]         runtime~main
runtime~main.92925a1b04b3b982ca9f.bundle.js.map   34.7 KiB  runtime~main  [emitted] [dev]               runtime~main
    vendors~main.92925a1b04b3b982ca9f.bundle.js   2.57 MiB  vendors~main  [emitted] [immutable]  [big]  vendors~main
vendors~main.92925a1b04b3b982ca9f.bundle.js.map   2.56 MiB  vendors~main  [emitted] [dev]               vendors~main
Entrypoint main [big] = runtime~main.92925a1b04b3b982ca9f.bundle.js runtime~main.92925a1b04b3b982ca9f.bundle.js.map vendors~main.92925a1b04b3b982ca9f.bundle.js vendors~main.92925a1b04b3b982ca9f.bundle.js.map main.92925a1b04b3b982ca9f.bundle.js main.92925a1b04b3b982ca9f.bundle.js.map
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true 88 bytes {main} [built]
[./.storybook/generated-entry.js] 238 bytes {main} [built]
[./.storybook/preview.js] 26 bytes {main} [built]
[./node_modules/@storybook/addon-knobs/dist/index.js] 6.3 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js] 149 bytes {vendors~main} [built]
[./node_modules/@storybook/client-api/dist/index.js] 3.82 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main} [built]
[./node_modules/@storybook/core/node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {vendors~main} [built]
[./node_modules/@storybook/core/node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
[./node_modules/@storybook/react/dist/client/index.js] 1.34 KiB {vendors~main} [built]
[./node_modules/airbnb-js-shims/index.js] 40 bytes {vendors~main} [built]
[./node_modules/core-js/features/symbol/index.js] 359 bytes {vendors~main} [built]
[./node_modules/global/window.js] 232 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true] 7.68 KiB {vendors~main} [built]
    + 786 hidden modules

WARNING in ./src/components/Task.js
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):

  Line 22:11:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid


 @ ./src/components/Task.stories.js 5:0-26 7:13-17 27:42-46 39:61-65 51:63-67
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./src/components/InboxScreen.stories.js
Module not found: Error: Can't resolve 'react-redux' in '/Users/takeshi/workspace/learnstorybook-code/src/components'
 @ ./src/components/InboxScreen.stories.js 4:0-39 13:57-65
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./src/components/InboxScreen.js
Module not found: Error: Can't resolve 'react-redux' in '/Users/takeshi/workspace/learnstorybook-code/src/components'
 @ ./src/components/InboxScreen.js 4:0-38 117:15-22
 @ ./src/components/InboxScreen.stories.js
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./src/components/TaskList.js
Module not found: Error: Can't resolve 'react-redux' in '/Users/takeshi/workspace/learnstorybook-code/src/components'
 @ ./src/components/TaskList.js 5:0-38 193:15-22
 @ ./src/components/TaskList.stories.js
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.48 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/@storybook/core/node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 2.13 KiB {HtmlWebpackPlugin_0} [built]

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

webpack building...
webpack built 02dfec856c1d61cb56cb in 4499ms
✖ ｢wdm｣: Hash: 02dfec856c1d61cb56cb
Version: webpack 4.43.0
Time: 4499ms
Built at: 2020-06-07 20:12:39
                                          Asset       Size        Chunks                                      Chunk Names
           92925a1b04b3b982ca9f.hot-update.json   35 bytes                [emitted] [immutable] [hmr]         
                            asset-manifest.json  640 bytes                [emitted]                           
                                    iframe.html   2.87 KiB                [emitted]                           
            main.02dfec856c1d61cb56cb.bundle.js   60.5 KiB          main  [emitted] [immutable]               main
        main.02dfec856c1d61cb56cb.bundle.js.map     36 KiB          main  [emitted] [dev]                     main
    runtime~main.02dfec856c1d61cb56cb.bundle.js   33.5 KiB  runtime~main  [emitted] [immutable]               runtime~main
runtime~main.02dfec856c1d61cb56cb.bundle.js.map   34.7 KiB  runtime~main  [emitted] [dev]                     runtime~main
    vendors~main.02dfec856c1d61cb56cb.bundle.js   2.57 MiB  vendors~main  [emitted] [immutable]        [big]  vendors~main
vendors~main.02dfec856c1d61cb56cb.bundle.js.map   2.56 MiB  vendors~main  [emitted] [dev]                     vendors~main
Entrypoint main [big] = runtime~main.02dfec856c1d61cb56cb.bundle.js runtime~main.02dfec856c1d61cb56cb.bundle.js.map vendors~main.02dfec856c1d61cb56cb.bundle.js vendors~main.02dfec856c1d61cb56cb.bundle.js.map main.02dfec856c1d61cb56cb.bundle.js main.02dfec856c1d61cb56cb.bundle.js.map
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true 88 bytes {main}
[./.storybook/generated-entry.js] 238 bytes {main} [built]
[./.storybook/preview.js] 26 bytes {main}
[./node_modules/@storybook/addon-knobs/dist/index.js] 6.3 KiB {vendors~main}
[./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js] 149 bytes {vendors~main}
[./node_modules/@storybook/client-api/dist/index.js] 3.82 KiB {vendors~main}
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main}
[./node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main}
[./node_modules/@storybook/core/node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {vendors~main}
[./node_modules/@storybook/core/node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {vendors~main}
[./node_modules/@storybook/react/dist/client/index.js] 1.34 KiB {vendors~main}
[./node_modules/airbnb-js-shims/index.js] 40 bytes {vendors~main}
[./node_modules/core-js/features/symbol/index.js] 359 bytes {vendors~main}
[./node_modules/global/window.js] 232 bytes {vendors~main}
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true] 7.68 KiB {vendors~main}
    + 786 hidden modules

WARNING in ./src/components/Task.js
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):

  Line 22:11:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid


 @ ./src/components/Task.stories.js 5:0-26 7:13-17 27:42-46 39:61-65 51:63-67
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./src/components/InboxScreen.stories.js
Module not found: Error: Can't resolve 'react-redux' in '/Users/takeshi/workspace/learnstorybook-code/src/components'
 @ ./src/components/InboxScreen.stories.js 4:0-39 13:57-65
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./src/components/InboxScreen.js
Module not found: Error: Can't resolve 'react-redux' in '/Users/takeshi/workspace/learnstorybook-code/src/components'
 @ ./src/components/InboxScreen.js 4:0-38 117:15-22
 @ ./src/components/InboxScreen.stories.js
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./src/components/TaskList.js
Module not found: Error: Can't resolve 'react-redux' in '/Users/takeshi/workspace/learnstorybook-code/src/components'
 @ ./src/components/TaskList.js 5:0-38 193:15-22
 @ ./src/components/TaskList.stories.js
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
✖ ｢wdm｣: Hash: a4856ed9839766846fcc
Version: webpack 4.43.0
Time: 18011ms
Built at: 2020-06-07 20:12:39
                                      Asset      Size        Chunks                                Chunk Names
                                 index.html  2.37 KiB                [emitted]                     
        main.1b5c1ff32ca6719d381c.bundle.js   5.9 KiB          main  [emitted] [immutable]         main
runtime~main.99691078705b39185f99.bundle.js  6.12 KiB  runtime~main  [emitted] [immutable]         runtime~main
vendors~main.5f8916f8958a3547ac1f.bundle.js  7.96 MiB  vendors~main  [emitted] [immutable]  [big]  vendors~main
Entrypoint main [big] = runtime~main.99691078705b39185f99.bundle.js vendors~main.5f8916f8958a3547ac1f.bundle.js main.1b5c1ff32ca6719d381c.bundle.js
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./node_modules/@storybook/addon-knobs/dist/register.js ./node_modules/@storybook/addon-actions/register.js ./node_modules/@storybook/addon-links/register.js ./.storybook/design-addon/register.js 88 bytes {main} [built]
[./.storybook/design-addon/register.js] 3.18 KiB {main} [built] [failed] [1 error]
[./node_modules/@storybook/addon-actions/dist/manager.js] 2.22 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/register.js] 38 bytes {vendors~main} [built]
[./node_modules/@storybook/addon-knobs/dist/components/Panel.js] 14.8 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-knobs/dist/register.js] 2.04 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-knobs/dist/shared.js] 837 bytes {vendors~main} [built]
[./node_modules/@storybook/addon-links/dist/manager.js] 2.1 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-links/register.js] 38 bytes {vendors~main} [built]
[./node_modules/@storybook/addons/dist/public_api.js] 2.23 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/client/manager/conditional-polyfills.js] 2.56 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/client/manager/index.js] 521 bytes {vendors~main} [built]
[./node_modules/@storybook/core/dist/client/manager/provider.js] 4.13 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/@storybook/ui/dist/index.js] 3.26 KiB {vendors~main} [built]
    + 1946 hidden modules

ERROR in ./.storybook/design-addon/register.js
Module build failed (from ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/takeshi/workspace/learnstorybook-code/.storybook/design-addon/register.js: Unexpected token (29:11)

  27 |   if (url.match(/\.(png|gif|jpeg|tiff|svg|anpg|webp)/)) {
  28 |     // do image viewer
> 29 |     return <Img alt="" src={url} />;
     |            ^
  30 |   }
  31 | 
  32 |   return <Iframe title={url} src={url} />;
    at Parser._raise (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:742:17)
    at Parser.raiseWithData (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:735:17)
    at Parser.raise (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:729:17)
    at Parser.unexpected (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:8779:16)
    at Parser.parseExprAtom (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:10074:20)
    at Parser.parseExprSubscripts (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:9624:23)
    at Parser.parseMaybeUnary (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:9604:21)
    at Parser.parseExprOps (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:9474:23)
    at Parser.parseMaybeConditional (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:9447:23)
    at Parser.parseMaybeAssign (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:9402:21)
    at Parser.parseExpression (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:9354:23)
    at Parser.parseReturnStatement (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:11471:28)
    at Parser.parseStatementContent (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:11152:21)
    at Parser.parseStatement (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:11104:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:11679:25)
    at Parser.parseBlockBody (/Users/takeshi/workspace/learnstorybook-code/node_modules/@babel/parser/lib/index.js:11665:10)
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./node_modules/@storybook/addon-knobs/dist/register.js ./node_modules/@storybook/addon-actions/register.js ./node_modules/@storybook/addon-links/register.js ./.storybook/design-addon/register.js main[5]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.48 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/@storybook/core/node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 2.13 KiB {HtmlWebpackPlugin_0} [built]
WARN force closed preview build

```

</details>

**Comment by akm** [comment]
Storybookの基本的な使い方はなんとなくわかったのでクローズ。

**Comment by akm** [comment]
続きは #24 と #25 としてIssue作成した。
